# Generated by Django 5.1.6 on 2025-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
