# Generated by Django 5.1.6 on 2025-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_shift_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
